#!/bin/sh

help() {
    echo "commands:"
    echo "  get        <link>"
    echo "  create     <url>"
    echo "  set        <link> <url>"
    echo "  force-set  <link> <url>"
    echo "  delete     <link>"
    echo "  delete-all <url>"
    echo "  stop       (local server)"
    echo "append curl arguments at the end"
    exit
}

auth() { [ -n "$NLN_AUTH_TOKEN" ] || { echo auth token not set; exit 1; }; }
cmd() { [ -n "$2" ] || help; "$@"; }
cmd2() { [ -n "$2" -a -n "$3" ] || help; "$@"; }

get() {
    l=$1; shift
    curl "$@" "$NLN_ENDPOINT/$l?read=true"
}
create() {
    l=$1; shift
    curl "$@" -X POST "$NLN_ENDPOINT" -H "Authorization: Bearer $NLN_AUTH_TOKEN" -d "$l"
}
set_() {
    l=$1; u=$2; shift 2
    curl "$@" -X PUT "$NLN_ENDPOINT/$l" -H "Authorization: Bearer $NLN_AUTH_TOKEN" -d "$u"
}
force_set() {
    l=$1; u=$2; shift 2
    curl "$@" -X PUT "$NLN_ENDPOINT/$l?force=true" -H "Authorization: Bearer $NLN_AUTH_TOKEN" -d "$u"
}
delete() {
    l=$1; shift
    curl "$@" -X DELETE "$NLN_ENDPOINT/$l" -H "Authorization: Bearer $NLN_AUTH_TOKEN"
}
delete_all() {
    u=$1; shift
    curl "$@" -X POST "$NLN_ENDPOINT/?delete=true" -H "Authorization: Bearer $NLN_AUTH_TOKEN" -d "$u"
}

command -v curl > /dev/null || { echo curl not found; exit 1; }
[ -n "$NLN_ENDPOINT" ] || NLN_ENDPOINT=http://127.0.0.1:6174

cmd=$1; shift
case $cmd in
    get)              cmd  get        "$@";;
    create)     auth; cmd  create     "$@";;
    set)        auth; cmd2 set_       "$@";;
    force-set)  auth; cmd2 force_set  "$@";;
    delete)     auth; cmd  delete     "$@";;
    delete-all) auth; cmd  delete_all "$@";;
    stop)             killall -i nln      ;;
    *) help;;
esac
